/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DbgClient_H
#define DbgClient_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "debug_proto_z80_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class DbgClientIf {
 public:
  virtual ~DbgClientIf() {}
  virtual void start_event() = 0;
  virtual void pause_event(const int32_t address, const std::map<int32_t, int32_t> & changed) = 0;
  virtual void stop_event(const std::map<int32_t, int32_t> & changed) = 0;
};

class DbgClientIfFactory {
 public:
  typedef DbgClientIf Handler;

  virtual ~DbgClientIfFactory() {}

  virtual DbgClientIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DbgClientIf* /* handler */) = 0;
};

class DbgClientIfSingletonFactory : virtual public DbgClientIfFactory {
 public:
  DbgClientIfSingletonFactory(const ::std::shared_ptr<DbgClientIf>& iface) : iface_(iface) {}
  virtual ~DbgClientIfSingletonFactory() {}

  virtual DbgClientIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DbgClientIf* /* handler */) {}

 protected:
  ::std::shared_ptr<DbgClientIf> iface_;
};

class DbgClientNull : virtual public DbgClientIf {
 public:
  virtual ~DbgClientNull() {}
  void start_event() {
    return;
  }
  void pause_event(const int32_t /* address */, const std::map<int32_t, int32_t> & /* changed */) {
    return;
  }
  void stop_event(const std::map<int32_t, int32_t> & /* changed */) {
    return;
  }
};


class DbgClient_start_event_args {
 public:

  DbgClient_start_event_args(const DbgClient_start_event_args&);
  DbgClient_start_event_args& operator=(const DbgClient_start_event_args&);
  DbgClient_start_event_args() {
  }

  virtual ~DbgClient_start_event_args() noexcept;

  bool operator == (const DbgClient_start_event_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DbgClient_start_event_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DbgClient_start_event_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DbgClient_start_event_pargs {
 public:


  virtual ~DbgClient_start_event_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DbgClient_pause_event_args__isset {
  _DbgClient_pause_event_args__isset() : address(false), changed(false) {}
  bool address :1;
  bool changed :1;
} _DbgClient_pause_event_args__isset;

class DbgClient_pause_event_args {
 public:

  DbgClient_pause_event_args(const DbgClient_pause_event_args&);
  DbgClient_pause_event_args& operator=(const DbgClient_pause_event_args&);
  DbgClient_pause_event_args() : address(0) {
  }

  virtual ~DbgClient_pause_event_args() noexcept;
  int32_t address;
  std::map<int32_t, int32_t>  changed;

  _DbgClient_pause_event_args__isset __isset;

  void __set_address(const int32_t val);

  void __set_changed(const std::map<int32_t, int32_t> & val);

  bool operator == (const DbgClient_pause_event_args & rhs) const
  {
    if (!(address == rhs.address))
      return false;
    if (!(changed == rhs.changed))
      return false;
    return true;
  }
  bool operator != (const DbgClient_pause_event_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DbgClient_pause_event_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DbgClient_pause_event_pargs {
 public:


  virtual ~DbgClient_pause_event_pargs() noexcept;
  const int32_t* address;
  const std::map<int32_t, int32_t> * changed;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DbgClient_stop_event_args__isset {
  _DbgClient_stop_event_args__isset() : changed(false) {}
  bool changed :1;
} _DbgClient_stop_event_args__isset;

class DbgClient_stop_event_args {
 public:

  DbgClient_stop_event_args(const DbgClient_stop_event_args&);
  DbgClient_stop_event_args& operator=(const DbgClient_stop_event_args&);
  DbgClient_stop_event_args() {
  }

  virtual ~DbgClient_stop_event_args() noexcept;
  std::map<int32_t, int32_t>  changed;

  _DbgClient_stop_event_args__isset __isset;

  void __set_changed(const std::map<int32_t, int32_t> & val);

  bool operator == (const DbgClient_stop_event_args & rhs) const
  {
    if (!(changed == rhs.changed))
      return false;
    return true;
  }
  bool operator != (const DbgClient_stop_event_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DbgClient_stop_event_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DbgClient_stop_event_pargs {
 public:


  virtual ~DbgClient_stop_event_pargs() noexcept;
  const std::map<int32_t, int32_t> * changed;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class DbgClientClient : virtual public DbgClientIf {
 public:
  DbgClientClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  DbgClientClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void start_event();
  void send_start_event();
  void pause_event(const int32_t address, const std::map<int32_t, int32_t> & changed);
  void send_pause_event(const int32_t address, const std::map<int32_t, int32_t> & changed);
  void stop_event(const std::map<int32_t, int32_t> & changed);
  void send_stop_event(const std::map<int32_t, int32_t> & changed);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DbgClientProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<DbgClientIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DbgClientProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_start_event(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_pause_event(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_stop_event(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DbgClientProcessor(::std::shared_ptr<DbgClientIf> iface) :
    iface_(iface) {
    processMap_["start_event"] = &DbgClientProcessor::process_start_event;
    processMap_["pause_event"] = &DbgClientProcessor::process_pause_event;
    processMap_["stop_event"] = &DbgClientProcessor::process_stop_event;
  }

  virtual ~DbgClientProcessor() {}
};

class DbgClientProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DbgClientProcessorFactory(const ::std::shared_ptr< DbgClientIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< DbgClientIfFactory > handlerFactory_;
};

class DbgClientMultiface : virtual public DbgClientIf {
 public:
  DbgClientMultiface(std::vector<std::shared_ptr<DbgClientIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DbgClientMultiface() {}
 protected:
  std::vector<std::shared_ptr<DbgClientIf> > ifaces_;
  DbgClientMultiface() {}
  void add(::std::shared_ptr<DbgClientIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void start_event() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->start_event();
    }
    ifaces_[i]->start_event();
  }

  void pause_event(const int32_t address, const std::map<int32_t, int32_t> & changed) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->pause_event(address, changed);
    }
    ifaces_[i]->pause_event(address, changed);
  }

  void stop_event(const std::map<int32_t, int32_t> & changed) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->stop_event(changed);
    }
    ifaces_[i]->stop_event(changed);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class DbgClientConcurrentClient : virtual public DbgClientIf {
 public:
  DbgClientConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  DbgClientConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void start_event();
  void send_start_event();
  void pause_event(const int32_t address, const std::map<int32_t, int32_t> & changed);
  void send_pause_event(const int32_t address, const std::map<int32_t, int32_t> & changed);
  void stop_event(const std::map<int32_t, int32_t> & changed);
  void send_stop_event(const std::map<int32_t, int32_t> & changed);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
